---
recipient: nobody@example.com

spring:
  mail:
    host: localhost
    port: 25

---
spring:
  profiles: cloud
  mail:
    host: ${vcap.services.smtp-service.credentials.hostname}
    username: ${vcap.services.smtp-service.credentials.username}
    password: ${vcap.services.smtp-service.credentials.password}
